// Combines the two front-end builds into a single publish directory, so the
// storefront and the staff dashboard can be served from one domain:
//
//   dist/          <- apps/web/dist     (customer storefront, "/")
//   dist/admin/    <- apps/staff/dist   (staff dashboard, "/admin")
//
// They stay separate builds on purpose. Merging them into one bundle would make
// every customer download the dashboard code, which is both slower and more
// than they need to know about the admin surface.

import { access, cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "dist");

const sources = [
  { from: path.join(root, "apps", "web", "dist"), to: outDir, name: "storefront" },
  { from: path.join(root, "apps", "staff", "dist"), to: path.join(outDir, "admin"), name: "dashboard" }
];

for (const { from, name } of sources) {
  try {
    await access(from);
  } catch {
    console.error(`Missing build output for the ${name}: ${from}`);
    console.error("Run the app builds first (npm run build:web && npm run build:staff).");
    process.exit(1);
  }
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

for (const { from, to, name } of sources) {
  await cp(from, to, { recursive: true });
  console.log(`${name.padEnd(10)} ${path.relative(root, from)} -> ${path.relative(root, to) || "dist"}`);
}

// Routing and headers are written into the output rather than left in a
// host-specific config file. Netlify and Cloudflare Pages both read _redirects
// and _headers from the published directory, so the same build deploys to
// either one — which matters when a free tier runs out mid-project.
//
// Only syntax both hosts accept: status 200 means "rewrite", and real files
// take precedence over rules, so assets still resolve. No "!" force suffix —
// that is Netlify-only, and Cloudflare rejects the entire file when it sees
// one rather than skipping the line.
//
// There is deliberately no /api rule. Netlify allowed a 404 there as a guard
// against a build shipping without VITE_API_BASE_URL, but Cloudflare supports
// neither that status nor the force suffix it needed. The guard that actually
// matters lives in apiClient.ts, which refuses to start rather than firing
// relative requests at the site itself.
//
// Storefront client-side routes, listed explicitly. A "/*" catch-all would be
// shorter, but it also swallows /admin/* — and every attempt to carve the
// dashboard back out ahead of it failed on Cloudflare: rewriting /admin/* to
// /admin/index.html is self-referential and gets discarded, while a copy at
// /admin.html collides with the /admin/ directory and 308-loops, because
// Cloudflare serves "admin.html" at "/admin".
//
// So nothing here matches /admin. Those paths fall through to the per-directory
// 404.html written below, which is the dashboard itself.
//
// Keep this in step with the routes in apps/web/src/App.tsx.
const redirects = `# Generated by scripts/assemble-site.mjs — do not edit by hand.
# Keep in step with the routes in apps/web/src/App.tsx.

/products  /index.html  200
/products/*  /index.html  200
/cart  /index.html  200
/checkout  /index.html  200
/orders/*  /index.html  200
/login  /index.html  200
/register  /index.html  200
/account/*  /index.html  200
`;

const headers = `# Generated by scripts/assemble-site.mjs — do not edit by hand.

# Vite fingerprints asset filenames, so they can be cached forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

/admin/assets/*
  Cache-Control: public, max-age=31536000, immutable

/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin

# The dashboard should never appear in search results.
/admin/*
  X-Robots-Tag: noindex, nofollow
`;

// Cloudflare serves the nearest 404.html, walking up from the requested path.
// That is what routes the dashboard: /admin/orders matches no rule and no file,
// so admin/404.html answers it — and that file is the dashboard's entry point.
// The root 404.html does the same for any storefront path not listed above.
//
// These are served with a 404 status rather than 200. For the dashboard that is
// irrelevant: it sits behind a login and should not be indexed anyway. The
// storefront's real routes are rewritten properly above, so only genuinely
// unknown URLs land here.
const dashboardEntry = await readFile(path.join(outDir, "admin", "index.html"), "utf8");
const storefrontEntry = await readFile(path.join(outDir, "index.html"), "utf8");
await writeFile(path.join(outDir, "admin", "404.html"), dashboardEntry);
await writeFile(path.join(outDir, "404.html"), storefrontEntry);

await writeFile(path.join(outDir, "_redirects"), redirects);
await writeFile(path.join(outDir, "_headers"), headers);
console.log("config     _redirects, _headers, 404.html, admin/404.html -> dist");

console.log("Site assembled in dist/");
