// Combines the two front-end builds into a single publish directory, so the
// storefront and the staff dashboard can be served from one domain:
//
//   dist/          <- apps/web/dist     (customer storefront, "/")
//   dist/admin/    <- apps/staff/dist   (staff dashboard, "/admin")
//
// They stay separate builds on purpose. Merging them into one bundle would make
// every customer download the dashboard code, which is both slower and more
// than they need to know about the admin surface.

import { access, cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "dist");

const sources = [
  { from: path.join(root, "apps", "web", "dist"), to: outDir, name: "storefront" },
  { from: path.join(root, "apps", "staff", "dist"), to: path.join(outDir, "admin"), name: "dashboard" }
];

for (const { from, name } of sources) {
  try {
    await access(from);
  } catch {
    console.error(`Missing build output for the ${name}: ${from}`);
    console.error("Run the app builds first (npm run build:web && npm run build:staff).");
    process.exit(1);
  }
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

for (const { from, to, name } of sources) {
  await cp(from, to, { recursive: true });
  console.log(`${name.padEnd(10)} ${path.relative(root, from)} -> ${path.relative(root, to) || "dist"}`);
}

// Routing and headers are written into the output rather than left in a
// host-specific config file. Netlify and Cloudflare Pages both read _redirects
// and _headers from the published directory, so the same build deploys to
// either one — which matters when a free tier runs out mid-project.
//
// Order is significant: the first matching rule wins, so /api and /admin have
// to precede the catch-all. "!" forces a rule to apply even when a file exists.
const redirects = `# Generated by scripts/assemble-site.mjs — do not edit by hand.

# The API is on another host entirely. Without this, a bundle built without
# VITE_API_BASE_URL would have its relative /api calls answered by index.html
# with status 200, and the app would parse HTML as JSON.
/api/*  /api-not-hosted-here  404!

# Staff dashboard (its own SPA, mounted at /admin).
# The bare /admin needs its own rule: "/admin/*" does not match it, and without
# this it falls through to the storefront catch-all below. Netlify happens to
# 301 /admin to /admin/ before rules run, which hid this; Cloudflare Pages does
# not, so relying on that would have broken the dashboard on the move.
/admin  /admin/index.html  200
/admin/*  /admin/index.html  200

# Customer storefront.
/*  /index.html  200
`;

const headers = `# Generated by scripts/assemble-site.mjs — do not edit by hand.

# Vite fingerprints asset filenames, so they can be cached forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

/admin/assets/*
  Cache-Control: public, max-age=31536000, immutable

/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin

# The dashboard should never appear in search results.
/admin/*
  X-Robots-Tag: noindex, nofollow
`;

await writeFile(path.join(outDir, "_redirects"), redirects);
await writeFile(path.join(outDir, "_headers"), headers);
console.log("config     _redirects, _headers -> dist");

console.log("Site assembled in dist/");
